是否开启玩家加入信息提示: "true"
玩家加入: "玩家{player}加入了游戏"
OP加入: "OP{OP}加入了游戏"
是否开启玩家退出信息提示: "true"
玩家退出: "玩家{player}退出了游戏"
OP退出: "OP{OP}退出了游戏"
死亡不掉落物品: "true"
死亡不掉落经验: "true"
是否记录指令: "true"
ConfigVersion: "1.0.1"#请勿随意更改！！！！